export const LOAD_URL= 'LOAD_URL';

export const LOAD_NEW_ATTEMPT= 'LOAD_NEW_ATTEMPT';
export const LOAD_NEW_SUCCESS= 'LOAD_NEW_SUCCESS';
export const LOAD_NEW_FAIL= 'LOAD_NEW_FAIL';

export const LOAD_LIKES_ATTEMPT = 'LOAD_LIKES_ATTEMPT';
export const LOAD_LIKES_SUCCESS = 'LOAD_LIKES_SUCCESS';
export const LOAD_LIKES_FAIL = 'LOAD_LIKES_FAIL';

export const LOAD_DISLIKES_ATTEMPT = 'LOAD_DISLIKES_ATTEMPT';
export const LOAD_DISLIKES_SUCCESS = 'LOAD_DISLIKES_SUCCESS';
export const LOAD_DISLIKES_FAIL = 'LOAD_DISLIKES_FAIL';

export const LOAD_FB_ATTEMPT = 'LOAD_FB_ATTEMPT';
export const LOAD_FB_SUCCESS = 'LOAD_FB_SUCCESS';
export const LOAD_FB_FAIL = 'LOAD_FB_FAIL';

export const LOAD_TWITTER_ATTEMPT = 'LOAD_TWITTER_ATTEMPT';
export const LOAD_TWITTER_SUCCESS = 'LOAD_TWITTER_SUCCESS';
export const LOAD_TWITTER_FAIL = 'LOAD_TWITTER_FAIL';

export const LOAD_LENGUAJE_ATTEMPT = 'LOAD_LENGUAJE_ATTEMPT';
export const LOAD_LENGUAJE_SUCCESS = 'LOAD_LENGUAJE_SUCCESS';
export const LOAD_LENGUAJE_FAIL = 'LOAD_LENGUAJE_FAIL';

export const LOAD_VERACITY_ATTEMPT = "LOAD_VERACITY_ATTEMPT";
export const LOAD_VERACITY_SUCCESS = "LOAD_VERACITY_SUCCESS";
export const LOAD_VERACITY_FAIL = "LOAD_VERACITY_FAIL"

export const LOAD_LIKE_SUCCESS = "LOAD_LIKE_SUCCESS";
export const LOAD_LIKE_ATTEMPT = "LOAD_LIKE_ATTEMPT";
export const LOAD_LIKE_FAIL = "LOAD_LIKE_FAIL";

export const LOAD_DISLIKE_ATTEMPT = 'LOAD_DISLIKE_ATTEMPT';
export const LOAD_DISLIKE_SUCCESS = 'LOAD_DISLIKE_SUCCESS';
export const LOAD_DISLIKE_FAIL = 'LOAD_DISLIKE_FAIL';